import {
  ProductItem,
  GoogleSheetConfig,
  GoogleDriveAsset,
  CalendarEventItem,
  FacebookPageChannel,
  ConversationItem,
  OrderItem,
  Workflow,
  WorkflowExecutionLog,
  Tenant,
  FacebookChannelConfig,
  AnalyticsData,
  Workspace,
} from './types';

export const initialProducts: ProductItem[] = [
  {
    id: 'prod_1',
    sku: 'P001',
    name: 'Premium Oxford Cotton Shirt',
    price: 850,
    stock: 28,
    sizes: ['M', 'L', 'XL'],
    colors: ['White', 'Sky Blue', 'Charcoal'],
    delivery: '৳60 Inside Dhaka (24-48h), ৳120 Outside Dhaka (2-3 days)',
    description: '100% combed cotton classic formal and semi-casual shirt. Breathable fabric tailored for BD weather.',
    category: 'Menswear',
    imageUrl: 'https://picsum.photos/seed/shirt1/600/600',
    driveFileId: 'drive_file_p001_oxford',
    driveFolder: '/Products/P001_Oxford/',
    updatedAt: '2026-09-20T14:30:00Z',
  },
  {
    id: 'prod_2',
    sku: 'P002',
    name: 'Raw Denim Slim Fit Jeans',
    price: 1450,
    stock: 14,
    sizes: ['30', '32', '34', '36'],
    colors: ['Deep Navy', 'Washed Blue'],
    delivery: '৳60 Inside Dhaka (24-48h), ৳120 Outside Dhaka (2-3 days)',
    description: '12.5oz stretch denim with reinforced stitching and antique brass buttons.',
    category: 'Menswear',
    imageUrl: 'https://picsum.photos/seed/jeans2/600/600',
    driveFileId: 'drive_file_p002_jeans',
    driveFolder: '/Products/P002_Denim/',
    updatedAt: '2026-09-20T14:30:00Z',
  },
  {
    id: 'prod_3',
    sku: 'P003',
    name: 'Breathable Pique Cotton Polo',
    price: 550,
    stock: 42,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Burgundy', 'Olive Green', 'Jet Black', 'Pure White'],
    delivery: '৳60 Inside Dhaka, ৳120 Outside Dhaka',
    description: '220 GSM combed pique polo shirt with ribbed collar and dual side slits.',
    category: 'Casuals',
    imageUrl: 'https://picsum.photos/seed/polo3/600/600',
    driveFileId: 'drive_file_p003_polo',
    driveFolder: '/Products/P003_Polo/',
    updatedAt: '2026-09-21T02:15:00Z',
  },
  {
    id: 'prod_4',
    sku: 'P004',
    name: 'Water-Resistant Commuter Backpack',
    price: 1890,
    stock: 7,
    sizes: ['24L One Size'],
    colors: ['Matte Black', 'Graphite Grey'],
    delivery: '৳60 Inside Dhaka (Cash on delivery available)',
    description: 'Ergonomic backpack with padded 15.6" laptop compartment and water-repellent zippers.',
    category: 'Bags & Accessories',
    imageUrl: 'https://picsum.photos/seed/bag4/600/600',
    driveFileId: 'drive_file_p004_backpack',
    driveFolder: '/Products/P004_Backpack/',
    updatedAt: '2026-09-19T09:00:00Z',
  },
  {
    id: 'prod_5',
    sku: 'P005',
    name: 'Genuine Leather Bifold Wallet',
    price: 950,
    stock: 19,
    sizes: ['Standard'],
    colors: ['Vintage Tan', 'Espresso Brown'],
    delivery: '৳60 Inside Dhaka, ৳120 Outside Dhaka',
    description: 'Top-grain Bangladeshi cowhide leather wallet with 8 card slots and currency divider.',
    category: 'Accessories',
    imageUrl: 'https://picsum.photos/seed/wallet5/600/600',
    driveFileId: 'drive_file_p005_wallet',
    driveFolder: '/Products/P005_Wallet/',
    updatedAt: '2026-09-21T05:00:00Z',
  },
];

export const initialSheetConfig: GoogleSheetConfig = {
  spreadsheetId: '1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgvE2upms',
  spreadsheetName: 'Apex_Mart_Inventory_Master_2026',
  worksheetTitle: 'Products_Live',
  lastSyncedAt: 'Just now',
  syncStatus: 'synced',
  rowCount: 5,
  columns: [
    'sku',
    'product_name',
    'price',
    'stock',
    'sizes',
    'colors',
    'delivery',
    'description',
    'drive_image_id',
  ],
  mapping: {
    sku: 'sku',
    product_name: 'product_name',
    price: 'price',
    stock: 'stock',
    sizes: 'sizes',
    colors: 'colors',
    delivery: 'delivery',
    description: 'description',
    drive_image_id: 'drive_image_id',
  },
};

export const initialDriveAssets: GoogleDriveAsset[] = [
  {
    id: 'drive_file_p001_oxford',
    name: 'P001_Oxford_Shirt_White_Front.jpg',
    mimeType: 'image/jpeg',
    thumbnailLink: 'https://picsum.photos/seed/shirt1/300/300',
    webViewLink: 'https://drive.google.com/file/d/p001_oxford/view',
    skuMatch: 'P001',
    fileSize: '1.8 MB',
    modifiedTime: '2026-09-18T10:15:00Z',
  },
  {
    id: 'drive_file_p002_jeans',
    name: 'P002_Raw_Denim_Navy_Studio.jpg',
    mimeType: 'image/jpeg',
    thumbnailLink: 'https://picsum.photos/seed/jeans2/300/300',
    webViewLink: 'https://drive.google.com/file/d/p002_jeans/view',
    skuMatch: 'P002',
    fileSize: '2.4 MB',
    modifiedTime: '2026-09-19T11:20:00Z',
  },
  {
    id: 'drive_file_p003_polo',
    name: 'P003_Pique_Polo_Collection.jpg',
    mimeType: 'image/jpeg',
    thumbnailLink: 'https://picsum.photos/seed/polo3/300/300',
    webViewLink: 'https://drive.google.com/file/d/p003_polo/view',
    skuMatch: 'P003',
    fileSize: '3.1 MB',
    modifiedTime: '2026-09-20T08:05:00Z',
  },
  {
    id: 'drive_file_p004_backpack',
    name: 'P004_Commuter_Backpack_Compartments.png',
    mimeType: 'image/png',
    thumbnailLink: 'https://picsum.photos/seed/bag4/300/300',
    webViewLink: 'https://drive.google.com/file/d/p004_backpack/view',
    skuMatch: 'P004',
    fileSize: '4.2 MB',
    modifiedTime: '2026-09-17T16:40:00Z',
  },
  {
    id: 'drive_file_p005_wallet',
    name: 'P005_Leather_Wallet_GiftBox.jpg',
    mimeType: 'image/jpeg',
    thumbnailLink: 'https://picsum.photos/seed/wallet5/300/300',
    webViewLink: 'https://drive.google.com/file/d/p005_wallet/view',
    skuMatch: 'P005',
    fileSize: '1.5 MB',
    modifiedTime: '2026-09-21T01:10:00Z',
  },
];

export const initialCalendarEvents: CalendarEventItem[] = [
  {
    id: 'cal_event_1',
    title: 'Customer Callback: Tanvir Ahmed (Order #1084)',
    description: 'Discuss size exchange for P001 Oxford Shirt. Customer requested call at 5:00 PM.',
    startAt: '2026-09-22T11:00:00Z', // 5:00 PM Dhaka time
    endAt: '2026-09-22T11:30:00Z',
    customerName: 'Tanvir Ahmed',
    customerPhone: '+880 1712-345678',
    status: 'confirmed',
    conversationId: 'conv_1',
  },
  {
    id: 'cal_event_2',
    title: 'Wholesale Inquiry Call: Farhan Textile',
    description: 'Bulk order inquiry for 50 Pique Polos (P003)',
    startAt: '2026-09-23T08:30:00Z',
    endAt: '2026-09-23T09:00:00Z',
    customerName: 'Farhan Kabir',
    customerPhone: '+880 1819-987654',
    status: 'confirmed',
    conversationId: 'conv_3',
  },
];

export const initialFacebookPages: FacebookPageChannel[] = [
  {
    id: 'fb_page_1',
    name: 'Apex Mart BD Official',
    pageId: '104829381920194',
    category: 'E-commerce Brand & Retail',
    status: 'connected',
    webhookSubscribed: true,
    followersCount: 48600,
    lastActive: '2 mins ago',
  },
  {
    id: 'fb_page_2',
    name: 'Glamour Trends Lifestyle',
    pageId: '984712039481922',
    category: 'Clothing Brand',
    status: 'connected',
    webhookSubscribed: true,
    followersCount: 19300,
    lastActive: '18 mins ago',
  },
];

export const initialConversations: ConversationItem[] = [
  {
    id: 'conv_1',
    customer: {
      id: 'cust_1',
      name: 'Tanvir Ahmed',
      psid: 'psid_8471928374',
      phone: '+880 1712-345678',
      email: 'tanvir.ahmed@gmail.com',
      address: 'House 42, Road 11, Dhanmondi, Dhaka',
      ordersCount: 2,
      totalSpent: 3150,
      tags: ['VIP Customer', 'Dhaka-Central', 'P001 Buyer'],
      lastActive: '5 mins ago',
    },
    lastMessage: 'ভাইয়া কাল বিকাল ৫টায় কি আমাকে একটা কল করতে পারবেন সাইজ কনফার্ম করার জন্য?',
    lastMessageTime: '10:45 AM',
    unreadCount: 1,
    aiActive: true,
    assignedAgent: 'AI Automated Engine',
    status: 'active',
    notes: 'Customer prefers calls in afternoon. High repeat buyer potential.',
    messages: [
      {
        id: 'msg_1_1',
        sender: 'customer',
        content: 'আসসালামু আলাইকুম, আপনাদের Premium Oxford Shirt এর দাম কত এবং ডেলিভারি চার্জ কত?',
        timestamp: '10:41 AM',
        intent: 'price_inquiry',
      },
      {
        id: 'msg_1_2',
        sender: 'ai',
        content: 'ওয়ালাইকুম আসসালাম স্যার! আমাদের Premium Oxford Cotton Shirt (SKU: P001) এর মূল্য মাত্র ৳৮৫০ টাকা।\n\nডেলিভারি চার্জ:\n• ঢাকা সিটির ভেতরে: ৳৬০ টাকা (১-২ কার্যদিবস)\n• ঢাকার বাইরে: ৳১২০ টাকা (২-৩ কার্যদিবস)\n\nবর্তমানে White, Sky Blue এবং Charcoal কালারে M, L, XL সাইজ স্টকে এভেইলএবল আছে। আপনি কি অর্ডার করতে চান?',
        timestamp: '10:41 AM',
        intent: 'price_inquiry',
        groundedFactsUsed: ['P001 price 850', 'Delivery Dhaka 60', 'Delivery Outside 120', 'Sizes M, L, XL'],
        confidence: 0.98,
      },
      {
        id: 'msg_1_3',
        sender: 'customer',
        content: 'ভাইয়া কাল বিকাল ৫টায় কি আমাকে একটা কল করতে পারবেন সাইজ কনফার্ম করার জন্য?',
        timestamp: '10:45 AM',
        intent: 'callback_schedule',
      },
      {
        id: 'msg_1_4',
        sender: 'ai',
        content: 'হ্যাঁ অবশ্যই স্যার! আপনার জন্য আগামীকাল বিকাল ৫:০০ টায় আমাদের কাস্টমার কেয়ার প্রতিনিধির সাথে একটি কল শিডিউল করে দিচ্ছি। আপনার ফোন নম্বরটি কি 01712-345678 এই নম্বরে থাকবে?',
        timestamp: '10:45 AM',
        intent: 'callback_schedule',
        groundedFactsUsed: ['Google Calendar slot check', 'Customer Phone lookup'],
        confidence: 0.96,
      },
    ],
  },
  {
    id: 'conv_2',
    customer: {
      id: 'cust_2',
      name: 'Nusrat Jahan',
      psid: 'psid_9281734910',
      phone: '+880 1892-112233',
      address: 'CDA Avenue, Nasirabad, Chattogram',
      ordersCount: 1,
      totalSpent: 1450,
      tags: ['Chattogram', 'Denim'],
      lastActive: '30 mins ago',
    },
    lastMessage: 'আমার অর্ডার টা কি কনফার্ম হয়েছে?',
    lastMessageTime: '10:20 AM',
    unreadCount: 0,
    aiActive: true,
    assignedAgent: 'AI Automated Engine',
    status: 'active',
    notes: 'Order #ORD-1082 confirmed. Tracking sent.',
    messages: [
      {
        id: 'msg_2_1',
        sender: 'customer',
        content: 'Hi, do you have size 32 in Raw Denim Jeans?',
        timestamp: '10:12 AM',
        intent: 'stock_inquiry',
      },
      {
        id: 'msg_2_2',
        sender: 'ai',
        content: 'Hello Nusrat! Yes, our Raw Denim Slim Fit Jeans (SKU: P002) is currently in stock in size 32 (14 pairs remaining). The price is ৳1,450, available in Deep Navy and Washed Blue colors. Would you like to place an order?',
        timestamp: '10:12 AM',
        intent: 'stock_inquiry',
        groundedFactsUsed: ['P002 stock 14', 'size 32 available', 'price 1450'],
        confidence: 0.99,
      },
      {
        id: 'msg_2_3',
        sender: 'customer',
        content: 'আমার অর্ডার টা কি কনফার্ম হয়েছে?',
        timestamp: '10:20 AM',
        intent: 'order_status',
      },
      {
        id: 'msg_2_4',
        sender: 'ai',
        content: 'জি ম্যাম! আপনার অর্ডার #ORD-1082 (Raw Denim Jeans - Size 32, Deep Navy) সফলভাবে কনফার্ম করা হয়েছে। মোট মূল্য ৳১,৫৭০ (৳১,৪৫০ + ৳১২০ ডেলিভারি চার্জ)। পার্সেলটি চট্টগ্রাম ঠিকানায় পাঠানো হচ্ছে এবং ২-৩ কার্যদিবসের মধ্যে ডেলিভারি সম্পন্ন হবে। ক্যাশ অন ডেলিভারি সুবিধা পাবেন।',
        timestamp: '10:20 AM',
        intent: 'order_status',
        groundedFactsUsed: ['Order ORD-1082 status confirmed', 'Shipping to Chattogram 120'],
        confidence: 0.97,
      },
    ],
  },
  {
    id: 'conv_3',
    customer: {
      id: 'cust_3',
      name: 'Rahim Ullah',
      psid: 'psid_2847192831',
      phone: '+880 1911-554433',
      address: 'GEC Circle, Chattogram',
      ordersCount: 0,
      totalSpent: 0,
      tags: ['New Lead', 'Customization Request'],
      lastActive: '1 hour ago',
    },
    lastMessage: 'I want to talk with a human manager about bulk corporate gift discount',
    lastMessageTime: '09:30 AM',
    unreadCount: 2,
    aiActive: false, // Human taken over
    assignedAgent: 'Kazi Shakil (Senior Support)',
    status: 'waiting_human',
    notes: 'Bulk purchase inquiry for 100 leather wallets. Transferred to corporate sales manager.',
    messages: [
      {
        id: 'msg_3_1',
        sender: 'customer',
        content: 'I want to talk with a human manager about bulk corporate gift discount for 100 leather wallets with custom logo embossing.',
        timestamp: '09:30 AM',
        intent: 'human_support',
      },
      {
        id: 'msg_3_2',
        sender: 'ai',
        content: 'I have transferred this conversation to our senior accounts manager Kazi Shakil. Since custom embossing requires corporate approval, an agent will assist you shortly here.',
        timestamp: '09:31 AM',
        intent: 'human_support',
        groundedFactsUsed: ['Handoff trigger: custom embossing & >50 units bulk inquiry'],
        confidence: 0.95,
      },
    ],
  },
];

export const initialOrders: OrderItem[] = [
  {
    id: 'ord_1',
    orderNumber: 'ORD-1084',
    customerName: 'Tanvir Ahmed',
    customerPhone: '+880 1712-345678',
    shippingAddress: 'House 42, Road 11, Dhanmondi, Dhaka',
    items: [
      {
        sku: 'P001',
        productName: 'Premium Oxford Cotton Shirt',
        quantity: 2,
        price: 850,
        variant: 'Size L / White & Sky Blue',
      },
    ],
    subtotal: 1700,
    deliveryFee: 60,
    total: 1760,
    status: 'pending_confirmation',
    createdAt: '2026-09-21T04:42:00Z',
    sourceChannel: 'Facebook Messenger (AI Agent)',
  },
  {
    id: 'ord_2',
    orderNumber: 'ORD-1083',
    customerName: 'Mahir Faisal',
    customerPhone: '+880 1688-445566',
    shippingAddress: 'Sector 4, Road 7, Uttara, Dhaka',
    items: [
      {
        sku: 'P004',
        productName: 'Water-Resistant Commuter Backpack',
        quantity: 1,
        price: 1890,
        variant: 'Matte Black (24L)',
      },
    ],
    subtotal: 1890,
    deliveryFee: 60,
    total: 1950,
    status: 'confirmed',
    createdAt: '2026-09-20T18:15:00Z',
    sourceChannel: 'Facebook Messenger (AI Agent)',
  },
  {
    id: 'ord_3',
    orderNumber: 'ORD-1082',
    customerName: 'Nusrat Jahan',
    customerPhone: '+880 1892-112233',
    shippingAddress: 'CDA Avenue, Nasirabad, Chattogram',
    items: [
      {
        sku: 'P002',
        productName: 'Raw Denim Slim Fit Jeans',
        quantity: 1,
        price: 1450,
        variant: 'Size 32 / Deep Navy',
      },
    ],
    subtotal: 1450,
    deliveryFee: 120,
    total: 1570,
    status: 'processing',
    createdAt: '2026-09-20T12:30:00Z',
    sourceChannel: 'Facebook Messenger (AI Agent)',
  },
  {
    id: 'ord_4',
    orderNumber: 'ORD-1081',
    customerName: 'Sabrina Mostafa',
    customerPhone: '+880 1755-998877',
    shippingAddress: 'Sylhet Sadar, Kumarpara, Sylhet',
    items: [
      {
        sku: 'P005',
        productName: 'Genuine Leather Bifold Wallet',
        quantity: 1,
        price: 950,
        variant: 'Vintage Tan',
      },
    ],
    subtotal: 950,
    deliveryFee: 120,
    total: 1070,
    status: 'shipped',
    createdAt: '2026-09-19T09:20:00Z',
    sourceChannel: 'Facebook Messenger (AI Agent)',
  },
];

export const initialWorkflows: Workflow[] = [
  {
    id: 'wf_1',
    name: 'AI Product & Stock Assistant',
    description: 'Grounds customer inquiries in real Google Sheets inventory and replies directly with price, stock, variants, and delivery charge.',
    isActive: true,
    version: '1.2.0',
    updatedAt: '2026-09-20T15:00:00Z',
    nodes: [
      {
        id: 'node_1',
        type: 'trigger_messenger',
        name: 'Messenger Trigger',
        description: 'Receives customer message from connected Facebook Page',
        x: 60,
        y: 180,
        config: { page: 'Apex Mart BD Official' },
      },
      {
        id: 'node_2',
        type: 'ai_intent_classifier',
        name: 'Intent Classifier',
        description: 'Analyzes intent (Product, Stock, Price, Size, Delivery, Order)',
        x: 320,
        y: 180,
        config: { model: 'gemini-3.8-flash', languages: ['bn', 'en', 'banglish'] },
      },
      {
        id: 'node_3',
        type: 'data_google_sheets',
        name: 'Google Sheets Lookup',
        description: 'Queries live inventory row by matched SKU or product title',
        x: 580,
        y: 120,
        config: { sheetId: 'Products_Live', exactMatchFirst: true },
      },
      {
        id: 'node_4',
        type: 'data_google_drive',
        name: 'Google Drive Media',
        description: 'Attaches authenticated high-res product photo from SKU folder',
        x: 580,
        y: 280,
        config: { folderMatch: 'sku' },
      },
      {
        id: 'node_5',
        type: 'ai_grounded_agent',
        name: 'Grounded Response Generator',
        description: 'Formulates polite, zero-hallucination reply in Bangla/English',
        x: 840,
        y: 180,
        config: { strictAntiHallucination: true, allowVariantPrompts: true },
      },
      {
        id: 'node_6',
        type: 'action_messenger_reply',
        name: 'Send Messenger Reply',
        description: 'Dispatches finalized message and product card back to customer',
        x: 1100,
        y: 180,
        config: { sendTypingIndicator: true },
      },
    ],
    edges: [
      { id: 'e1', source: 'node_1', target: 'node_2' },
      { id: 'e2', source: 'node_2', target: 'node_3', label: 'Product Inquiry' },
      { id: 'e3', source: 'node_3', target: 'node_4' },
      { id: 'e4', source: 'node_3', target: 'node_5' },
      { id: 'e5', source: 'node_4', target: 'node_5' },
      { id: 'e6', source: 'node_5', target: 'node_6' },
    ],
  },
  {
    id: 'wf_2',
    name: 'Customer Callback & Calendar Scheduler',
    description: 'Detects customer request for a phone call, checks Google Calendar availability, books appointment, and sends confirmation.',
    isActive: true,
    version: '1.0.4',
    updatedAt: '2026-09-21T06:00:00Z',
    nodes: [
      {
        id: 'node_c1',
        type: 'trigger_messenger',
        name: 'Messenger Trigger',
        description: 'Incoming message requesting a call or delivery slot',
        x: 60,
        y: 180,
        config: { channel: 'Messenger' },
      },
      {
        id: 'node_c2',
        type: 'ai_intent_classifier',
        name: 'Extract Date & Time',
        description: 'Parses requested time (e.g., "কাল বিকাল ৫টায়")',
        x: 320,
        y: 180,
        config: { timezone: 'Asia/Dhaka' },
      },
      {
        id: 'node_c3',
        type: 'data_calendar_check',
        name: 'Google Calendar Availability',
        description: 'Verifies no conflicting appointment in primary calendar',
        x: 580,
        y: 180,
        config: { calendar: 'primary', durationMins: 30 },
      },
      {
        id: 'node_c4',
        type: 'action_calendar_book',
        name: 'Create Calendar Event',
        description: 'Inserts scheduled event with customer name, phone, and context',
        x: 840,
        y: 180,
        config: { titleTemplate: 'Customer Callback: {{customer_name}}' },
      },
      {
        id: 'node_c5',
        type: 'action_messenger_reply',
        name: 'Send Booking Confirmation',
        description: 'Sends confirmation text with scheduled time in Dhaka format',
        x: 1100,
        y: 180,
        config: {},
      },
    ],
    edges: [
      { id: 'ec1', source: 'node_c1', target: 'node_c2' },
      { id: 'ec2', source: 'node_c2', target: 'node_c3' },
      { id: 'ec3', source: 'node_c3', target: 'node_c4', label: 'Slot Available' },
      { id: 'ec4', source: 'node_c4', target: 'node_c5' },
    ],
  },
  {
    id: 'wf_3',
    name: 'Order Collection & Auto-Checkout',
    description: 'Walks customer through SKU selection, size/color variant choice, delivery address capture, and creates an order record.',
    isActive: true,
    version: '1.1.0',
    updatedAt: '2026-09-18T12:00:00Z',
    nodes: [
      {
        id: 'node_o1',
        type: 'trigger_messenger',
        name: 'Messenger Trigger',
        description: 'Customer indicates intent to buy',
        x: 60,
        y: 180,
        config: {},
      },
      {
        id: 'node_o2',
        type: 'ai_grounded_agent',
        name: 'Collect Address & Phone',
        description: 'Politely prompts for Bangladeshi mobile number and delivery district',
        x: 320,
        y: 180,
        config: { validateBDPhone: true },
      },
      {
        id: 'node_o3',
        type: 'data_google_sheets',
        name: 'Calculate Delivery & Total',
        description: 'Applies ৳60 for Dhaka or ৳120 for outside districts',
        x: 580,
        y: 180,
        config: {},
      },
      {
        id: 'node_o4',
        type: 'action_create_order',
        name: 'Create Order Record',
        description: 'Generates ORD-XXXX order in New/Pending status',
        x: 840,
        y: 180,
        config: { requireHumanReview: false },
      },
      {
        id: 'node_o5',
        type: 'action_messenger_reply',
        name: 'Send Order Summary',
        description: 'Provides invoice breakdown and estimated delivery window',
        x: 1100,
        y: 180,
        config: {},
      },
    ],
    edges: [
      { id: 'eo1', source: 'node_o1', target: 'node_o2' },
      { id: 'eo2', source: 'node_o2', target: 'node_o3' },
      { id: 'eo3', source: 'node_o3', target: 'node_o4' },
      { id: 'eo4', source: 'node_o4', target: 'node_o5' },
    ],
  },
  {
    id: 'wf_4',
    name: 'Smart Human Escalation & Handoff',
    description: 'Detects angry customer, custom pricing request, or low AI confidence and automatically notifies human agent.',
    isActive: true,
    version: '1.0.1',
    updatedAt: '2026-09-19T04:00:00Z',
    nodes: [
      {
        id: 'node_h1',
        type: 'trigger_messenger',
        name: 'Messenger Trigger',
        description: 'Incoming customer inquiry',
        x: 60,
        y: 180,
        config: {},
      },
      {
        id: 'node_h2',
        type: 'logic_condition',
        name: 'Check Confidence / Complaint',
        description: 'Is sentiment negative, human requested, or confidence < 0.85?',
        x: 320,
        y: 180,
        config: { threshold: 0.85 },
      },
      {
        id: 'node_h3',
        type: 'action_human_handoff',
        name: 'Pause AI & Alert Agent',
        description: 'Sets conversation status to waiting_human and sends sound/badge alert',
        x: 620,
        y: 180,
        config: { assignDepartment: 'Customer_Support' },
      },
      {
        id: 'node_h4',
        type: 'action_messenger_reply',
        name: 'Handoff Notification',
        description: 'Politely tells customer that a representative is taking over',
        x: 920,
        y: 180,
        config: {},
      },
    ],
    edges: [
      { id: 'eh1', source: 'node_h1', target: 'node_h2' },
      { id: 'eh2', source: 'node_h2', target: 'node_h3', label: 'Confidence < 85%' },
      { id: 'eh3', source: 'node_h3', target: 'node_h4' },
    ],
  },
];

export const initialExecutionLogs: WorkflowExecutionLog[] = [
  {
    id: 'exec_1092',
    workflowId: 'wf_1',
    triggerSource: 'Facebook Messenger',
    customerInput: 'ভাইয়া প্রিমিয়াম শার্টের দাম কত?',
    status: 'success',
    startedAt: '2026-09-21T07:11:00Z',
    completedAt: '2026-09-21T07:11:01Z',
    steps: [
      { nodeId: 'node_1', nodeName: 'Messenger Trigger', status: 'success', output: 'Message received from PSID: 8471928374', durationMs: 12 },
      { nodeId: 'node_2', nodeName: 'Intent Classifier', status: 'success', output: 'Intent: price_inquiry (Confidence: 0.98)', durationMs: 240 },
      { nodeId: 'node_3', nodeName: 'Google Sheets Lookup', status: 'success', output: 'Matched SKU: P001 (Price: ৳850, Stock: 28)', durationMs: 85 },
      { nodeId: 'node_4', nodeName: 'Google Drive Media', status: 'success', output: 'Resolved thumbnail: drive_file_p001_oxford', durationMs: 45 },
      { nodeId: 'node_5', nodeName: 'Grounded Response Generator', status: 'success', output: 'Grounded reply composed in Bangla', durationMs: 310 },
      { nodeId: 'node_6', nodeName: 'Send Messenger Reply', status: 'success', output: 'Delivered via Graph API 200 OK', durationMs: 95 },
    ],
  },
  {
    id: 'exec_1091',
    workflowId: 'wf_2',
    triggerSource: 'Facebook Messenger',
    customerInput: 'কাল বিকাল ৫টায় কি আমাকে কল করতে পারবেন?',
    status: 'success',
    startedAt: '2026-09-21T06:45:00Z',
    completedAt: '2026-09-21T06:45:02Z',
    steps: [
      { nodeId: 'node_c1', nodeName: 'Messenger Trigger', status: 'success', output: 'Text received: কাল বিকাল ৫টায়...', durationMs: 10 },
      { nodeId: 'node_c2', nodeName: 'Extract Date & Time', status: 'success', output: 'Extracted: Tomorrow 5:00 PM (Asia/Dhaka)', durationMs: 195 },
      { nodeId: 'node_c3', nodeName: 'Google Calendar Availability', status: 'success', output: 'Slot 17:00-17:30 is free on primary calendar', durationMs: 120 },
      { nodeId: 'node_c4', nodeName: 'Create Calendar Event', status: 'success', output: 'Event created: Customer Callback: Tanvir Ahmed', durationMs: 180 },
      { nodeId: 'node_c5', nodeName: 'Send Booking Confirmation', status: 'success', output: 'Messenger confirmation sent with event ID', durationMs: 65 },
    ],
  },
];

export const initialGoogleSheetConfig: GoogleSheetConfig = initialSheetConfig;

export const initialTenants: Tenant[] = [
  {
    id: 'tenant_1',
    name: 'Apex Mart BD',
    slug: 'apex-mart',
    customDomain: 'store.apexmartbd.com',
    plan: 'growth',
    createdAt: '2026-01-15T00:00:00Z',
    channelsCount: 2,
    ordersCount: 148,
    revenueBdt: 248900,
  },
  {
    id: 'tenant_2',
    name: 'Glamour Trends Lifestyle',
    slug: 'glamour-trends',
    plan: 'starter',
    createdAt: '2026-04-10T00:00:00Z',
    channelsCount: 1,
    ordersCount: 42,
    revenueBdt: 68500,
  },
  {
    id: 'tenant_3',
    name: 'Artisan Crafts & Leather',
    slug: 'artisan-crafts',
    plan: 'enterprise',
    createdAt: '2026-06-01T00:00:00Z',
    channelsCount: 4,
    ordersCount: 310,
    revenueBdt: 580000,
  },
];

export const initialFacebookChannels: FacebookChannelConfig[] = [
  {
    id: 'fb_chan_1',
    pageName: 'Apex Mart BD Official',
    pageId: '104829381920194',
    accessToken: 'EAAQ...bd_live_page_token',
    verifyToken: 'apex_mart_secret_verify_token_2026',
    isConnected: true,
    webhookStatus: 'active',
    subscribedFields: ['messages', 'messaging_postbacks', 'messaging_optins'],
  },
  {
    id: 'fb_chan_2',
    pageName: 'Glamour Trends Lifestyle',
    pageId: '984712039481922',
    accessToken: 'EAAQ...glamour_page_token',
    verifyToken: 'glamour_secret_verify_token_2026',
    isConnected: true,
    webhookStatus: 'active',
    subscribedFields: ['messages', 'messaging_postbacks'],
  },
];

export const mockAnalytics: AnalyticsData = {
  totalRevenue: 248900,
  totalOrders: 148,
  aiHandlingRate: 88.4,
  averageResponseTimeSeconds: 1.2,
  intentBreakdown: [
    { intent: 'Price & Stock Inquiry', count: 412, percentage: 42 },
    { intent: 'Product Image & Specs', count: 265, percentage: 27 },
    { intent: 'Delivery & Shipping', count: 176, percentage: 18 },
    { intent: 'Callback Scheduling', count: 78, percentage: 8 },
    { intent: 'Human Handoff Request', count: 49, percentage: 5 },
  ],
};

export const initialWorkspaces: Workspace[] = [
  {
    id: 'ws_1',
    name: 'Apex Mart BD',
    slug: 'apex-mart',
    businessType: 'Retail & Fashion',
    currency: 'BDT',
    timezone: 'Asia/Dhaka',
    sheetConnected: true,
    driveConnected: true,
    calendarConnected: true,
    createdAt: '2026-01-15T00:00:00Z',
  },
  {
    id: 'ws_2',
    name: 'Glamour Trends Lifestyle',
    slug: 'glamour-trends',
    businessType: 'Boutique Clothing',
    currency: 'BDT',
    timezone: 'Asia/Dhaka',
    sheetConnected: false,
    driveConnected: false,
    calendarConnected: false,
    createdAt: '2026-04-10T00:00:00Z',
  },
  {
    id: 'ws_3',
    name: 'Artisan Crafts & Leather',
    slug: 'artisan-crafts',
    businessType: 'Leather Crafts & Gifts',
    currency: 'BDT',
    timezone: 'Asia/Dhaka',
    sheetConnected: true,
    driveConnected: true,
    calendarConnected: false,
    createdAt: '2026-06-01T00:00:00Z',
  },
];


